# Generated by Django 5.1.1 on 2024-11-18 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(max_length=15, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(max_length=255)),
                ('state_jurisdiction_code', models.CharField(max_length=10)),
                ('state_jurisdiction', models.CharField(max_length=50)),
                ('central_jurisdiction_code', models.CharField(max_length=10)),
                ('central_jurisdiction', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('entity_type', models.CharField(max_length=50)),
                ('business_nature', models.JSONField()),
                ('principal_address', models.JSONField()),
                ('registration_date', models.CharField(blank=True, max_length=8, null=True)),
                ('last_updated', models.CharField(blank=True, max_length=8, null=True)),
                ('e_invoice_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyGSTRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(max_length=15)),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('trade_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_type', models.CharField(blank=True, max_length=255, null=True)),
                ('principal_address', models.JSONField()),
                ('registration_date', models.CharField(blank=True, max_length=10, null=True)),
                ('last_update', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=500, null=True)),
                ('date_of_filing', models.CharField(blank=True, max_length=10, null=True)),
                ('return_type', models.CharField(blank=True, max_length=20, null=True)),
                ('return_period', models.CharField(blank=True, max_length=20, null=True)),
                ('return_status', models.CharField(blank=True, max_length=20, null=True)),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('fetch_date', models.CharField(blank=True, max_length=20, null=True)),
                ('annual_turnover', models.IntegerField(blank=True, null=True)),
                ('delayed_filling', models.CharField(blank=True, max_length=20, null=True)),
                ('Delay_days', models.CharField(blank=True, max_length=20, null=True)),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GSTRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(max_length=15, unique=True)),
                ('business_name', models.CharField(max_length=255)),
                ('registration_date', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('trade_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_type', models.CharField(blank=True, max_length=255, null=True)),
                ('filing_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='FilingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.CharField(max_length=50)),
                ('filing_period', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('arn', models.CharField(max_length=50)),
                ('filing_date', models.CharField(blank=True, max_length=10, null=True)),
                ('gst_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gstrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_mode', models.CharField(max_length=20)),
                ('date_of_filing', models.DateField()),
                ('return_type', models.CharField(max_length=20)),
                ('return_period', models.CharField(max_length=10)),
                ('arn', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='api.companydetails')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delayed_filing', models.BooleanField(default=False)),
                ('average_delay_days', models.FloatField(default=0.0)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.companydetails')),
            ],
        ),
    ]
