# Generated by Django 5.1.1 on 2024-11-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companygstrecord',
            name='Delay_days',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
